[package]
name = "awer"
version = "0.1.0"
edition = "2018"
license = "GPL-3.0-only"
authors = ["Alexandre Courbot <gnurou@gmail.com>"]

[dependencies]
log = "0.4"
env_logger = "0.8"
byteorder = "1"
clap = "2"
piston = "0.52"
piston2d-graphics = "0.39"
piston2d-opengl_graphics = "0.76"
pistoncore-glutin_window = "0.67"

# Raster backend
image = "0.23"

# Uncomment for custom piston_graphics.
#[patch.crates-io]
#piston2d-graphics = { path = "../graphics" }

#piston-music = "0.25"